
service: auth-server

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  timeout: 60
  # in seconds, vs default of 6

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          method: get
          path: api/token/{code}
          cors:
            origins:
              -  "http://localhost:8080"
  getRefreshToken:
    handler: handler.getAccessToken
    events:
      - http:
          method: get
          path: api/refreshtoken/{code}
          cors:
            origins:
              -  "http://localhost:8080"
  